/**********************************************************************************************************************
 * \file onnx2c_math.h
 * \copyright Copyright (C) Infineon Technologies AG 2026
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ONNX2C_MATH_H
#define ONNX2C_MATH_H

#include <stdint.h>   /* uint32_t, int32_t */

#ifndef INFINITY
#  define INFINITY (1.0f / 0.0f)
#endif

/* C99-safe float/uint32_t */
typedef union { float f; uint32_t u; } onnx2c_fu32_t;

/* ---- fabsf/fmaxf/fminf: branchless, no libm ---- */
static inline float onnx2c_fabsf(float x)
{
  return x >= 0.0f ? x : -x;
}
static inline float onnx2c_fmaxf(float a, float b)
{
  return a > b ? a : b;
}
static inline float onnx2c_fminf(float a, float b)
{
  return a < b ? a : b;
}

static inline float
onnx2c_sqrtf(float x)
{
  if (x < 0.0f)
    return 0.0f / 0.0f;
  if (x == 0.0f)
    return 0.0f;
  onnx2c_fu32_t v = { x };
  v.u = (v.u >> 1) + 0x1FC00000u;
  float r = v.f;
  r = 0.5f * (r + x / r); r = 0.5f * (r + x / r); r = 0.5f * (r + x / r);
  return r;
}

static inline float
onnx2c_sqrtf_fast(float x)
{
  if (x < 0.0f)
    return 0.0f / 0.0f;
  if (x == 0.0f)
    return 0.0f;
  onnx2c_fu32_t v = { x };
  v.u = (v.u >> 1) + 0x1FC00000u;
  float r = v.f;
  r = 0.5f * (r + x / r); r = 0.5f * (r + x / r);
  return r;
}

/* ---- expf: range-reduce + Horner + exponent shift ---- */
/* default: <=1 ULP (6 Horner steps, degree-7); fast: ~10 ULP (4 steps, degree-5) */
static inline float
onnx2c_expf(float x)
{
  if (x > 88.722f)
    return INFINITY;
  if (x < -87.336f)
    return 0.0f;
  float xf = x * 1.442695040888963f;
  float n = (float)(int32_t)(xf + (xf >= 0.0f ? 0.5f : -0.5f));
  float r = x - n * 6.931471805599453e-1f;
  float p = 1.9875691500e-4f;
  p = p * r + 1.3981999507e-3f;
  p = p * r + 8.3334519073e-3f;
  p = p * r + 4.1665795894e-2f;
  p = p * r + 1.6666665459e-1f;
  p = p * r + 5.0000001201e-1f;
  p = r * r * p + r + 1.0f;
  onnx2c_fu32_t v = { p };
  v.u += (uint32_t)((int32_t)n) << 23;
  return v.f;
}
static inline float
onnx2c_expf_fast(float x)
{
  if (x > 88.722f)
    return INFINITY;
  if (x < -87.336f)
    return 0.0f;
  float xf = x * 1.442695040888963f;
  float n = (float)(int32_t)(xf + (xf >= 0.0f ? 0.5f : -0.5f));
  float r = x - n * 6.931471805599453e-1f;
  float p = 1.3981999507e-3f;
  p = p * r + 8.3334519073e-3f;
  p = p * r + 4.1665795894e-2f;
  p = p * r + 1.6666665459e-1f;
  p = p * r + 5.0000001201e-1f;
  p = r * r * p + r + 1.0f;
  onnx2c_fu32_t v = { p };
  v.u += (uint32_t)((int32_t)n) << 23;
  return v.f;
}

/* ---- logf: exponent strip + atanh series (4-term) ---- */
/* default: ~2 ULP (4-term atanh); fast: ~50 ULP (3-term) */
static inline float
onnx2c_logf(float x)
{
  if (x <= 0.0f)
    return x < 0.0f ? 0.0f / 0.0f : -INFINITY;
  onnx2c_fu32_t v = { x };
  if (v.u >= 0x7F800000u)
    return x;
  int32_t e = (int32_t)(v.u >> 23) - 127;
  v.u = (v.u & 0x007FFFFFu) | 0x3F800000u;
  float m = v.f;
  if (m > 1.41421356f)
    {
      m *= 0.5f; e++;
    }
  float s = (m - 1.0f) / (m + 1.0f);
  float s2 = s * s;
  float p = 2.0f * s * (1.0f + s2 * (3.333333343e-1f + s2 * (2.000000030e-1f + s2 * 1.428571429e-1f)));
  return (float)e * 6.931471805599453e-1f + p;
}
static inline float
onnx2c_logf_fast(float x)
{
  if (x <= 0.0f)
    return x < 0.0f ? 0.0f / 0.0f : -INFINITY;
  onnx2c_fu32_t v = { x };
  if (v.u >= 0x7F800000u)
    return x;
  int32_t e = (int32_t)(v.u >> 23) - 127;
  v.u = (v.u & 0x007FFFFFu) | 0x3F800000u;
  float m = v.f;
  if (m > 1.41421356f)
    {
      m *= 0.5f; e++;
    }
  float s = (m - 1.0f) / (m + 1.0f);
  float s2 = s * s;
  float p = 2.0f * s * (1.0f + s2 * (3.333333343e-1f + s2 * (2.000000030e-1f + s2 * 1.428571429e-1f)));
  return (float)e * 6.931471805599453e-1f + p;
}

/* ---- sinf: double quadrant-reduce + degree-9 Cephes Horner ---- */
/* default: 1 ULP (double reduce + degree-9/8 poly); fast: ~20 ULP, [-10,10] (float reduce + degree-7/6) */
static inline float
onnx2c_sinf(float x)
{
  double y = (double)x * 0.6366197723675814;
  int32_t n = (int32_t)(y >= 0.0 ? y + 0.5 : y - 0.5);
  float r = (float)((double)x - (double)n * 1.5707963267948966);
  float r2 = r * r;
  float s = r + r * r2 * (-1.6666654611e-1f + r2 * (8.3321608736e-3f + r2 * (-1.9515295891e-4f + r2 * 2.7557511498e-6f)));
  float c = 1.0f + r2 * (-4.9999997376e-1f + r2 * (4.1666571817e-2f + r2 * (-1.3887634106e-3f + r2 * 2.4430213965e-5f)));
  switch (n & 3)
    {
    case 0: return s;

    case 1: return c;

    case 2: return -s;

    default: return -c;
    }
}
static inline float
onnx2c_sinf_fast(float x)
{
  double y = (double)x * 0.6366197723675814;
  int32_t n = (int32_t)(y >= 0.0 ? y + 0.5 : y - 0.5);
  float r = (float)((double)x - (double)n * 1.5707963267948966);
  float r2 = r * r;
  float s = r + r * r2 * (-1.6666654611e-1f + r2 * (8.3321608736e-3f + r2 * (-1.9515295891e-4f + r2 * 2.7557511498e-6f)));
  float c = 1.0f + r2 * (-4.9999997376e-1f + r2 * (4.1666571817e-2f + r2 * (-1.3887634106e-3f + r2 * 2.4430213965e-5f)));
  switch (n & 3)
    {
    case 0: return s;

    case 1: return c;

    case 2: return -s;

    default: return -c;
    }
}

/* ---- cosf: double quadrant-reduce + degree-8 Cephes Horner ---- */
/* default: 1 ULP; fast: ~50 ULP, [-10,10], truncated sin sub-poly */
static inline float
onnx2c_cosf(float x)
{
  double y = (double)x * 0.6366197723675814;
  int32_t n = (int32_t)(y >= 0.0 ? y + 0.5 : y - 0.5);
  float r = (float)((double)x - (double)n * 1.5707963267948966);
  float r2 = r * r;
  float s = r + r * r2 * (-1.6666654611e-1f + r2 * (8.3321608736e-3f + r2 * (-1.9515295891e-4f + r2 * 2.7557511498e-6f)));
  float c = 1.0f + r2 * (-4.9999997376e-1f + r2 * (4.1666571817e-2f + r2 * (-1.3887634106e-3f + r2 * 2.4430213965e-5f)));
  switch (n & 3)
    {
    case 0: return c;

    case 1: return -s;

    case 2: return -c;

    default: return s;
    }
}
static inline float
onnx2c_cosf_fast(float x)
{
  double y = (double)x * 0.6366197723675814;
  int32_t n = (int32_t)(y >= 0.0 ? y + 0.5 : y - 0.5);
  float r = (float)((double)x - (double)n * 1.5707963267948966);
  float r2 = r * r;
  float s = r + r * r2 * (-1.6666654611e-1f + r2 * (8.3321608736e-3f + r2 * (-1.9515295891e-4f + r2 * 2.7557511498e-6f)));
  float c = 1.0f + r2 * (-4.9999997376e-1f + r2 * (4.1666571817e-2f + r2 * (-1.3887634106e-3f + r2 * 2.4430213965e-5f)));
  switch (n & 3)
    {
    case 0: return c;

    case 1: return -s;

    case 2: return -c;

    default: return s;
    }
}

/* ---- sigmoidf: 1/(1+exp(-x)), numerically stable ---- */
/* clamp at ±88.722: expf overflows outside this range, wrapping the exponent field */
static inline float
onnx2c_sigmoidf(float x)
{
  if (x > 88.722f)
    return 1.0f;
  if (x < -88.722f)
    return 0.0f;
  float e = onnx2c_expf(x >= 0.0f ? -x : x);
  return x >= 0.0f ? 1.0f / (1.0f + e) : e / (1.0f + e);
}
static inline float
onnx2c_sigmoidf_fast(float x)
{
  if (x > 88.722f)
    return 1.0f;
  if (x < -88.722f)
    return 0.0f;
  float e = onnx2c_expf_fast(x >= 0.0f ? -x : x);
  return x >= 0.0f ? 1.0f / (1.0f + e) : e / (1.0f + e);
}

/* ---- swishf: x * sigmoid(x) = x / (1 + exp(-x)) ---- */
static inline float
onnx2c_swishf(float x)
{
  return x * onnx2c_sigmoidf(x);
}

/* ---- tanhf: (1-exp(-2|x|))/(1+exp(-2|x|)), sign-symmetric ---- */
static inline float
onnx2c_tanhf(float x)
{
  if (x > 9.0f)
    return 1.0f;
  if (x < -9.0f)
    return -1.0f;
  float e = onnx2c_expf(-2.0f * (x >= 0.0f ? x : -x));
  float r = (1.0f - e) / (1.0f + e);
  return x >= 0.0f ? r : -r;
}
static inline float
onnx2c_tanhf_fast(float x)
{
  if (x > 9.0f)
    return 1.0f;
  if (x < -9.0f)
    return -1.0f;
  float e = onnx2c_expf_fast(-2.0f * (x >= 0.0f ? x : -x));
  float r = (1.0f - e) / (1.0f + e);
  return x >= 0.0f ? r : -r;
}

/* ---- erff: two-piece Horner, [0,1] in a^2, [1,4] in -|a| + exp identity ---- */
/* max error: 0.96922 ulp ([0,1]), 1.03872 ulp ([1,4]); no fast variant */
static inline float
onnx2c_erff(float a)
{
  float fa = a >= 0.0f ? a : -a;
  if (fa >= 4.0f)
    return a >= 0.0f ? 1.0f : -1.0f;
  const float c0_lo = 8.05854797e-5f, c1_lo = -8.07280652e-4f, c2_lo = 5.19511057e-3f;
  const float c3_lo = -2.68568154e-2f, c4_lo = 1.12836286e-1f, c5_lo = -3.76126260e-1f, c6_lo = 1.28379166e-1f;
  const float c0_up = 2.58684158e-5f, c1_up = 5.64930320e-4f, c2_up = 5.66849299e-3f;
  const float c3_up = 3.51767987e-2f, c4_up = 1.54329687e-1f, c5_up = -9.15674686e-1f, c6_up = 6.28459632e-1f;
  int hi = (fa >= 1.0f);
  float s = hi ? -fa : a * a;
  float t = hi ? -fa : a;
  float c0 = hi?c0_up:c0_lo, c1 = hi?c1_up:c1_lo, c2 = hi?c2_up:c2_lo, c3 = hi?c3_up:c3_lo;
  float c4 = hi?c4_up:c4_lo, c5 = hi?c5_up:c5_lo, c6 = hi?c6_up:c6_lo;
  float r = c0; r = r * s + c1; r = r * s + c2; r = r * s + c3; r = r * s + c4; r = r * s + c5; r = r * s + c6; r = r * t + t;
  if (hi)
    {
      onnx2c_fu32_t fua = { a }, fur;
      r = onnx2c_expf(0.693147180559945309f * r);
      r = 1.0f - r;
      fur.f = r;
      fur.u = (fua.u & 0x80000000u) | fur.u;
      return fur.f;
    }
  return r;
}

/* ---- floorf/ceilf/rintf: integer-only, no libm ---- */
static inline float
onnx2c_floorf(float x)
{
  /* if (x >= 8388608.0f || x <= -8388608.0f || x != x) return x; */
  int32_t i = (int32_t)x;
  return (float)(i - (x < (float)i ? 1 : 0));
}
static inline float
onnx2c_ceilf(float x)
{
  /* if (x >= 8388608.0f || x <= -8388608.0f || x != x) return x; */
  int32_t i = (int32_t)x;
  return (float)(i + (x > (float)i ? 1 : 0));
}
/* round half-away-from-zero (C roundf semantics) */
static inline float
onnx2c_roundf(float x)
{
  int32_t i = (int32_t)x; float f = x - (float)i;
  return (float)(i + (f >= 0.5f) - (f <= -0.5f));
}
/* round half-to-even via exponent-based bit clearing */
static inline float
onnx2c_rintf(float x)
{
  onnx2c_fu32_t v = { x };
  uint32_t e = (v.u >> 23) & 0xFFu, sign = v.u & 0x80000000u;
  if (e >= 150u)
    return x;                                                                  /* already integer / inf / nan */
  if (e < 126u)
    {
      v.u = sign; return v.f;
    }                                                                          /* |x| < 0.5 → ±0 */
  if (e == 126u)
    {
      v.u = (v.u & 0x7FFFFFu) ? (sign | 0x3F800000u) : sign; return v.f;
    }                                                                                   /* 0.5 <= |x| < 1 */
  uint32_t sh = 150u - e, half = 1u << (sh - 1u), mask = (1u << sh) - 1u;
  uint32_t frac = v.u & mask, lsb = (v.u >> sh) & 1u;
  v.u &= ~mask;
  if ((frac > half) | ((frac == half) & lsb))
    v.u += 1u << sh;
  return v.f;
}
/* round float to nearest int (half-to-even), returns int */
/* 2^23 add-subtract trick: requires FPU round-to-nearest-even mode */
static inline int
onnx2c_lrint(float x)
{
  float m = (x >= 0.0f) ? 8388608.0f : -8388608.0f;
  return (int)((x + m) - m);
}

/* ---- sinhf/coshf: composed from onnx2c_expf, ~5 ULP ---- */
static inline float
onnx2c_sinhf(float x)
{
  if (x > 88.722f)
    return INFINITY;
  if (x < -88.722f)
    return -INFINITY;
  float ep = onnx2c_expf(x), em = onnx2c_expf(-x);
  return 0.5f * (ep - em);
}
static inline float
onnx2c_coshf(float x)
{
  if (x > 88.722f || x < -88.722f)
    return INFINITY;
  float ep = onnx2c_expf(x), em = onnx2c_expf(-x);
  return 0.5f * (ep + em);
}

/* ---- tanf: same double reduction as sinf/cosf, ~2 ULP ---- */
static inline float
onnx2c_tanf(float x)
{
  double y = (double)x * 0.6366197723675814;
  int32_t n = (int32_t)(y >= 0.0 ? y + 0.5 : y - 0.5);
  float r = (float)((double)x - (double)n * 1.5707963267948966);
  float r2 = r * r;
  float s = r + r * r2 * (-1.6666654611e-1f + r2 * (8.3321608736e-3f + r2 * (-1.9515295891e-4f + r2 * 2.7557511498e-6f)));
  float c = 1.0f + r2 * (-4.9999997376e-1f + r2 * (4.1666571817e-2f + r2 * (-1.3887634106e-3f + r2 * 2.4430213965e-5f)));
  switch (n & 3)
    {
    case 0: return s / c;

    case 1: return -c / s;

    case 2: return s / c;

    default: return -c / s;
    }
}

/* ---- atanf: 3-way reduce to [0,tan(pi/8)]; degree-7 Horner on that range, ~2 ULP ---- */
static inline float
onnx2c_atanf(float x)
{
  float fa = x >= 0.0f ? x : -x, off = 0.0f, a; int sub = 0;
  if (fa > 2.41421356f)
    {
      a = 1.0f / fa;              off = 1.5707963267948966f; sub = 1;
    }
  else if (fa > 0.41421356f)
    {
      a = (fa - 1.0f) / (fa + 1.0f); off = 0.7853981633974483f;
    }
  else
    {
      a = fa;
    }
  float t = a * a;
  float p = 8.05374449538e-2f;
  p = p * t - 1.38776856032e-1f;
  p = p * t + 1.99777106478e-1f;
  p = p * t - 3.33329491539e-1f;
  p = a + a * t * p;
  float r = sub ? off - p : off + p;
  return x >= 0.0f ? r : -r;
}

/* ---- atanhf: poly for small |x|, separate logs for larger |x| ---- */
static inline float
onnx2c_atanhf(float x)
{
  float a = x >= 0.0f ? x : -x;
  if (a >= 1.0f)
    return x >= 0.0f ? INFINITY : -INFINITY;
  float r;
  if (a < 0.25f)
    {
      float t = a * a;
      float p = 7.6923077e-2f;      /* 1/13 */
      p = p * t + 9.0909091e-2f;    /* 1/11 */
      p = p * t + 1.1111111e-1f;    /* 1/9 */
      p = p * t + 1.4285714e-1f;    /* 1/7 */
      p = p * t + 2.0000000e-1f;    /* 1/5 */
      p = p * t + 3.3333333e-1f;    /* 1/3 */
      r = a + a * t * p;
    }
  else
    {
      r = 0.5f * (onnx2c_logf(1.0f + a) - onnx2c_logf(1.0f - a));
    }
  return x >= 0.0f ? r : -r;
}

/* ---- asinhf: degree-13 poly for small |x|, log+sqrt for larger ---- */
static inline float
onnx2c_asinhf(float x)
{
  float a = x >= 0.0f ? x : -x;
  float r;
  if (a < 0.5f)
    {
      float t = a * a;
      float p = 1.7352764e-2f;      /* x^12: 10395/599040 */
      p = p * t - 2.2372159e-2f;    /* x^10: -945/42240 */
      p = p * t + 3.0381944e-2f;    /* x^8:  105/3456 */
      p = p * t - 4.4642857e-2f;    /* x^6:  -15/336 */
      p = p * t + 7.5e-2f;          /* x^4:  3/40 */
      p = p * t - 1.6666667e-1f;    /* x^2:  -1/6 */
      r = a + a * t * p;
    }
  else
    {
      r = onnx2c_logf(a + onnx2c_sqrtf(a * a + 1.0f));
    }
  return x >= 0.0f ? r : -r;
}

/* ---- acoshf: 2*asinh(sqrt((x-1)/2)) near 1, log+sqrt for larger x ---- */
static inline float
onnx2c_acoshf(float x)
{
  if (x < 1.0f)
    return 0.0f / 0.0f;
  if (x < 2.0f)
    return 2.0f * onnx2c_asinhf(onnx2c_sqrtf(0.5f * (x - 1.0f)));
  return onnx2c_logf(x + onnx2c_sqrtf((x - 1.0f) * (x + 1.0f)));
}

/* ---- asinf/acosf: via atanf(x/sqrt(1-x^2)), ~3 ULP ---- */
static inline float
onnx2c_asinf(float x)
{
  float a = x >= 0.0f ? x : -x;
  if (a >= 1.0f)
    return x >= 0.0f ?  1.5707963267948966f : -1.5707963267948966f;
  float r = onnx2c_atanf(a / onnx2c_sqrtf((1.0f - a) * (1.0f + a)));
  return x >= 0.0f ? r : -r;
}
/* acosf: half-angle identity near ±1 avoids subtractive cancellation */
static inline float
onnx2c_acosf(float x)
{
  if (x > 0.5f)
    return 2.0f * onnx2c_asinf(onnx2c_sqrtf(0.5f * (1.0f - x)));
  if (x < -0.5f)
    return 3.14159265358979324f - 2.0f * onnx2c_asinf(onnx2c_sqrtf(0.5f * (1.0f + x)));
  return 1.5707963267948966f - onnx2c_asinf(x);
}

/* ---- fmodf: truncate-toward-zero remainder, no libm ---- */
static inline float
onnx2c_fmodf(float x, float y)
{
  float q = (float)(int32_t)(x / y);
  return x - q * y;
}

/* ---- powf: exp(y*log(x)) via onnx2c; handles negative x for integer y ---- */
/* special cases: y==0 → 1, x==0 → 0, x<0 non-integer y → NaN */
static inline float
onnx2c_powf(float x, float y)
{
  if (y == 0.0f)
    return 1.0f;
  if (x == 0.0f)
    return 0.0f;
  if (x < 0.0f)
    {
      int32_t n = (int32_t)y;
      if ((float)n != y)
        return 0.0f / 0.0f;                     /* non-integer exponent on negative base */
      float r = onnx2c_expf((float)n * onnx2c_logf(-x));
      return (n & 1) ? -r : r;
    }
  return onnx2c_expf(y * onnx2c_logf(x));
}

#endif /* ONNX2C_MATH_H */


